name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch like 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Specify the Python version you need

    - name: Install dependencies
      run: |
        pip install pdoc

    - name: Build documentation
      run: pdoc src/ --output-dir ./docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs # The directory containing the generated documentation
